### ISSUE TITLE
zmon-redis downtime

### ISSUE THREAD

**Issue by mohabusama** [zalando-incubator/kubernetes-on-aws#842] opened 2018-02-12 13:54 UTC
Since ``zmon-redis`` is running as a single pod, there are chances where the pod gets re-scheduled (autoscaling) and in turn leading to some unexpected behavior:

- Local alert state changes which could lead to inconsistent paging
- No check execution during the re-scheduling period

We have various alternatives afaik:

- Persist Redis data.
- Make sure Redis does not get rescheduled.
- Deploy an HA Redis.
- Switch to external Redis (e.g. ELC).
- ...?

**Comment by Jan-M** [comment] 2018-02-13 15:19
This is just another case of the auto-scaler not honoring and prioritizing nodes for termination.

If downscaling via cluster auto scaler would prefer nodes without statefulsets or nodes not impacting pod disruption budgets this could be easily prevented.

**Comment by szuecs** [comment] 2018-10-13 11:14
IMHO this is working by design in Kubernetes,  Pods can be terminated any time. Systems that have no operator, that takes ownership of failover to replica similar to https://github.com/zalando-incubator/postgres-operator are a bug itself if these can not run with more than 2 replicas and need a single write master.
Therefore closing this, because it has to be solved by the redis application owner

**Closed as completed by szuecs** 2018-10-13 11:14 UTC
