### ISSUE TITLE
Connection drops when doing kubectl `logs` or `exec`

### ISSUE THREAD

**Issue by mikkeloscar** [zalando-incubator/kubernetes-on-aws#49] opened 2016-10-28 13:04 UTC
I often see the connection drop when following the logs of a pod or when exec'ing into a pod.

This usually happens after 30-60 secs.

**Comment by hjacobs** [comment] 2016-11-17 09:45
I'll try to reproduce this too.

**Comment by hjacobs** [comment] 2016-11-17 12:25
This looks like idle timeout as it does not happen if we output something every 10s:

```
$ zalando-kubectl exec -it mypod bash
root@deploy01-0:/# while true; do sleep 10; date; done
Thu Nov 17 12:04:06 UTC 2016
...
Thu Nov 17 12:25:07 UTC 2016
```

**Comment by hjacobs** [comment] 2016-12-06 20:34
@mikkeloscar closing this for now --- I assume everybody is happy with the current 5 minutes idle timeout.

**Closed by hjacobs** 2016-12-06 20:34 UTC
Labels: bug
