### ISSUE TITLE
sshd unit failures

### ISSUE THREAD

**Issue by Raffo** [zalando-incubator/kubernetes-on-aws#136] opened 2016-11-21 17:04 UTC
When ssh connection fails, the instance report failed units: 

````
● sshd@x:22-y:z.service    loaded failed failed  OpenSSH per-connection server daemon (y:z)
````

**Comment by hjacobs** [comment] 2016-11-21 20:29
This is caused by CoreOS using systemd socket activation to start OpenSSH. We have at least two options to get rid of the unit failures:

* change the SSH port to avoid the usual flood of scans: https://coreos.com/os/docs/latest/customizing-sshd.html
* change from socket activation to "always-on" OpenSSH daemon

**Comment by Raffo** [comment] 2016-11-22 08:42
Or we can just do both, can't we?

**Comment by linki** [comment] 2016-11-22 09:01
what's the advantage of socket activation?

**Comment by mikkeloscar** [comment] 2017-05-30 16:27
We don't consider this a problem so will close it.

**Closed by mikkeloscar** 2017-05-30 16:27 UTC
